### ISSUE TITLE
the 'uncaughtException' handler exits with a success error code (0)

### ISSUE THREAD

**Issue by jpallen** [baoshan/fairy#9] opened 2014-03-30 15:02 UTC
Node normally exits with a non-zero error code when it crashes due to an exception, but the Fairy clean up code calls process.exit(), which then exists with a zero status code. I'm not sure what the appropriate exit code should be, (Node.js seems to use 8 in my preliminary testing) but it definitely shouldn't be zero.

**Comment by baoshan** [comment] 2014-05-16 05:53
The problem is fixed in `0.0.10`, exit with code `1` instead of `0` on `uncaughtException`. 

In `0.0.10`, the process who enqueues tasks also get task completion and progress callbacks.

Thanks.

**Closed as completed by baoshan** 2014-05-16 05:53 UTC
